service: weather-websocket

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:HeadObject
      Resource: 
        - "arn:aws:s3:::${env:BUCKET_NAME}"
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: non-linux
  LIGHTNING_SNS: arn:aws:sns:${env:DEFAULT_REGION}:${env:AWS_ID}:${env:LIGHTNING_SNS}

functions:
  connectHandler:
    handler: handler.connection
    events:
      - websocket: $connect
      - websocket: $disconnect
     
  default:
    handler: handler.default
    events:
      - websocket: $default

  subscription:
    handler: handler.subscribe
    events:
      - websocket: subscribe

  send-msg:
    handler: handler.broadcast_data
    events:
      - sns: ${self:custom.LIGHTNING_SNS}
